name: droplets

channels:
 - conda-forge
 - defaults

dependencies:
 - python 3.8.*
 - astropy 4.0.*
 - astroquery 0.4.*
 - matplotlib 3.1.*
 - numpy 1.18.*
 - jupyter 1.0.*
 - pandas 1.0.*
 - mkdocs 1.0.*
