site_name: Open Science Droplets
site_description: 'Material and references for training on reproducible and collaborative research'
site_author: 'Javier Moldon'
repo_url: 

nav:
    - Home: index.md
    - Quick Start: quickstart.md
    - Jupyter notebooks: jupyter.md
    - Collaborative science online, Github: github.md
    - Version control with git: git.md
    - Software management with conda (TBD): conda.md
    - Python interactive visualization (TBD): interactive.md
    - Binder (TBD): binder.md
    - Snakemake (TBD): snakemake.md
    - Containers (TBD): containers.md
    - Reproducibility examples (TBD): reproducibility.md
      #    - Testing: science.md
    - Resources (TBD): resources.md

#theme: 'material' # Excellent searcher. Too clear. Hard to find subsections
#theme: windmill    # Very good search bar. Clean navigation
#theme: readthedocs
theme:
    name: readthedocs
    highlightjs: true

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.arithmatex
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences


extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
